"use client";
import Link from"next/link";import{FormEvent,useState}from"react";
const nav=["About","Portfolio","Services","Contact"];
function Head(){return <header className="border-b border-zinc-200"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><Link href="/" className="font-serif text-3xl italic">Luma.</Link><nav className="hidden gap-6 text-xs uppercase tracking-[.18em] md:flex">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`}>{x}</Link>)}</nav><details className="relative md:hidden"><summary className="cursor-pointer list-none text-xs uppercase tracking-widest">Menu</summary><nav className="absolute right-0 z-10 mt-2 grid bg-[#171717] p-3 text-white">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`} className="px-4 py-2">{x}</Link>)}</nav></details></div></header>}
function Form(){const[s,setS]=useState(false);return <form onSubmit={(e:FormEvent)=>{e.preventDefault();setS(true)}} className="grid gap-4 bg-[#171717] p-7 text-white"><input required aria-label="Name" placeholder="Your name" className="border-b border-white/30 bg-transparent py-3 outline-none"/><input required aria-label="Email" type="email" placeholder="Email address" className="border-b border-white/30 bg-transparent py-3 outline-none"/><textarea required aria-label="Project idea" placeholder="What are you making?" rows={4} className="border-b border-white/30 bg-transparent py-3 outline-none"/><button className="w-fit border border-white px-5 py-3">{s?"Note received":"Send a note"}</button><p className="text-xs text-white/50">Demo form — no real client request is sent.</p></form>}
const d:Record<string,[string,string,string,React.ReactNode]>={
about:["About","A small studio with a wide lens.","A fictional independent creative practice for brands, people and cultural projects.",<><div className="grid gap-8 md:grid-cols-2"><p className="font-serif text-4xl leading-tight">The work moves between still images, motion, typography and the details that make a project feel like itself.</p><p className="leading-8 text-zinc-600">This concept demonstrates an editorial portfolio experience: spacious, visual and direct about what a creative collaborator can do.</p></div><div className="mt-14 grid gap-px bg-zinc-200 md:grid-cols-3">{[["Observe","Find the visual truth."],["Shape","Give the idea a recognisable direction."],["Make","Carry it across every needed format."]].map(([t,c],i)=><article key={t} className="bg-[#fbfbfa] p-7"><p className="text-xs text-zinc-400">0{i+1}</p><h2 className="mt-7 font-serif text-3xl">{t}</h2><p className="mt-4 leading-7 text-zinc-600">{c}</p></article>)}</div></>],
portfolio:["Portfolio","Selected work, imagined in full colour.","Fictional demo commissions that show a complete creative-portfolio structure.",<div className="grid gap-x-7 gap-y-14 md:grid-cols-2">{[["Northern Light","Brand film","photo-1531058020387-3be344556be6"],["Soft Geometry","Editorial","photo-1513364776144-60967b0f800f"],["Stills in Motion","Campaign","photo-1494438639946-1ebd1d20bf85"],["Objects & Air","Art direction","photo-1524758631624-e2822e304c36"],["Field Notes","Publication","photo-1519608487953-e999c86e7454"],["Quiet Hours","Hospitality","photo-1497366216548-37526070297c"]].map(([n,k,img],i)=><article key={n} className={i%2?"md:mt-16":""}><img src={`https://images.unsplash.com/${img}?auto=format&fit=crop&w=1100&q=85`} alt={n} className="aspect-[4/3] w-full object-cover"/><div className="mt-4 flex justify-between"><h2 className="font-serif text-3xl">{n}</h2><p className="pt-2 text-xs uppercase tracking-widest text-zinc-500">{k}</p></div><p className="mt-3 leading-7 text-zinc-600">A concise project story, clear creative direction and tailored visual delivery.</p></article>)}</div>],
services:["Services","A clear creative partner from thought to final asset.","Flexible ways to work together, shaped around the project’s size and rhythm.",<div className="divide-y divide-zinc-200 border-y border-zinc-200">{[["Creative Direction","A visual point of view that gives the whole project a coherent centre."],["Photography","Portraits, spaces and products with a tactile editorial approach."],["Visual Identity","A distinct but usable system for teams who need consistency."],["Campaign Worlds","Creative concepts across stills, motion and launch materials."]].map((x,i)=><article key={x[0]} className="grid gap-5 py-8 md:grid-cols-[.15fr_.55fr_.3fr]"><p className="text-zinc-400">0{i+1}</p><h2 className="font-serif text-4xl">{x[0]}</h2><p className="leading-7 text-zinc-600">{x[1]}</p></article>)}</div>],
contact:["Contact","Let’s make something worth looking at.","This inquiry experience is a fictional portfolio demonstration.",<div className="grid gap-10 md:grid-cols-[.75fr_1.25fr]"><div><p className="font-serif text-4xl">Available for select concept collaborations.</p><p className="mt-6 leading-8 text-zinc-600">hello@lumaportfolio.demo<br/>Fictional studio · Creative Quarter</p><p className="mt-8 text-sm text-zinc-500">All people, projects and data are fictional demo content.</p></div><Form/></div>]
};
export function Interior({page}:{page:string}){const s=d[page]??d.about;return <main className="min-h-screen bg-[#fbfbfa] text-[#171717]"><Head/><section className="mx-auto max-w-6xl px-6 py-16 md:py-24"><p className="text-xs uppercase tracking-[.25em] text-zinc-500">{s[0]}</p><h1 className="mt-6 max-w-5xl font-serif text-5xl leading-[.92] tracking-[-.05em] md:text-8xl">{s[1]}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-600">{s[2]}</p><div className="mt-16">{s[3]}</div></section><section className="bg-[#f1cbd4] px-6 py-12"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-5 md:flex-row"><p className="font-serif text-3xl">Good ideas deserve a good frame.</p><Link href="/contact" className="w-fit border border-[#171717] px-5 py-3">Start a project</Link></div></section><footer className="bg-[#171717] px-6 py-10 text-white"><div className="mx-auto flex max-w-6xl justify-between"><p className="font-serif text-3xl italic">Luma.</p><p className="text-sm text-white/60">Fictional creative portfolio · Demo project</p></div></footer></main>}
